/* Shared browser/server arithmetic. Values are indicative versioned assumptions, not quotes. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.SitePivotCommercial=factory()})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const VERSION='delivered-2026-10-06-v1',ROOMS={bedroom:14,masterSuite:30,bathroom:10,living:30,kitchenLiving:40,office:10,garage:36,upperLevel:100,other:0,laundry:8};
const numeric=n=>n!==null&&n!==''&&n!==undefined&&Number.isFinite(+n),positive=n=>numeric(n)&&+n>0;
function rateCard({quality='premium',configuration='two-storey',region='NSW',customRate}={}){const bands={standard:[4800,5600,6500],premium:[6000,6800,8000],luxury:[9200,10500,11800]},configs={'two-storey':[0,0,0],'two-storey-basement':[800,1200,1800],'three-level-basement':[1000,1500,2200]},b=bands[quality]||bands.premium,add=configs[configuration];if(!add&&!(configuration==='custom'&&positive(customRate)))return{status:'review',reason:'A custom configuration needs an explicit QS/builder delivered rate.'};const r=configuration==='custom'?[+customRate,+customRate,+customRate]:b.map((n,i)=>n+add[i]);return{status:'indicative',rateLow:r[0],rateMid:r[1],rateHigh:r[2],includedCosts:['construction','professional','approvals','externalWorks','contingency'],excludedCosts:['land','demolition','authorityContributions','finance','holding','selling','marketing','legal','taxSensitivity'],configuration,region,quality,version:VERSION,taxBasis:'Construction GST included; project GST/tax needs a separate accountant-approved net adjustment.',note:'Delivered rate includes construction, ordinary design/professional fees, approvals/reports, external works and construction contingency. Exceptional ground conditions, contributions, demolition and commercial costs need explicit confirmation. Basement premiums are indicative configuration assumptions.'}}
function deliveredCost(input={}){const r=input.rateCard||rateCard(input);if(r.status==='review'||!positive(input.area))return{...r,status:'review',low:null,mid:null,high:null,reason:r.reason||'Confirm total constructed area.'};return{...r,area:+input.area,low:+input.area*r.rateLow,mid:+input.area*r.rateMid,high:+input.area*r.rateHigh,constructionLow:+input.area*r.rateLow,constructionHigh:+input.area*r.rateHigh,professionalPct:0,approvalsPct:0,externalPct:0,contingencyPct:0,demolition:0,complexity:1}}
function feasibility(i={}){const bounded={holdingMonths:[0,600],interestRate:[0,1],landDebtRatio:[0,1],constructionDrawdown:[0,1],sellingPct:[0,1],taxPct:[0,1],targetProfitOnCost:[0,10],financeEstablishment:[0,Infinity],holding:[0,Infinity],marketing:[0,Infinity],legal:[0,Infinity]};for(const[k,[lo,hi]]of Object.entries(bounded))if(i[k]!=null&&(!numeric(i[k])||+i[k]<lo||+i[k]>hi))return{status:'review',reason:'Confirm valid finance, timing and commercial cost assumptions.'};if(!positive(i.land)||!positive(i.cost?.mid)||!i.products?.length||i.products.some(p=>!positive(p.value)||!Number.isInteger(+p.count)||+p.count<1))return{status:'review',reason:'Confirm land/current-property value, delivered cost and sold evidence or explicit user assumptions for each finished product.'};const grv=i.products.reduce((a,p)=>a+p.value*p.count,0),land=+i.land,delivery=i.cost.mid,lines={};for(const [key,val]of Object.entries(i.extras||{})){if(['demolition','professional','approvals','externalWorks','contingency','authorityContributions'].includes(key)&&(i.cost.excludedCosts||[]).includes(key)&&numeric(val)&&+val>=0)lines[key]=+val}
 const extras=Object.values(lines).reduce((a,b)=>a+b,0),years=(i.holdingMonths??18)/12,interest=i.interestRate??.07,landDebt=i.landDebtRatio??.7,draw=i.constructionDrawdown??.5,finance=(land*landDebt+(delivery+extras)*draw)*interest*years,establishment=i.financeEstablishment??20000,holding=i.holding??15000,selling=grv*(i.sellingPct??.025),marketing=i.marketing??10000,legal=i.legal??30000,taxSensitivity=grv*(i.taxPct??.04),nonLand=delivery+extras+(delivery+extras)*draw*interest*years+establishment+holding+selling+marketing+legal+taxSensitivity,landFactor=1+landDebt*interest*years,total=land+delivery+extras+finance+establishment+holding+selling+marketing+legal+taxSensitivity,profit=grv-total,target=i.targetProfitOnCost??.2,residual=(grv/(1+target)-nonLand)/landFactor;
 return{status:'indicative',grv,site:land,delivery,lines,finance,financeEstablishment:establishment,holding,selling,marketing,legal,taxSensitivity,total,profit,margin:profit,profitOnCost:profit/total,profitOnGrv:profit/grv,marginPct:profit/grv,residualLandValue:residual,holdingMonths:years*12,interestRate:interest,targetProfitOnCost:target,assumptions:{landDebtRatio:landDebt,constructionDrawdown:draw},note:'Simple staged drawdown sensitivity; financing terms, timing, excluded allowances and net GST/tax adjustment require professional confirmation. Residual assumes retained existing land (no acquisition duty), fixed construction costs and the stated target profit on cost.'}}
function roomArea(rooms={},override){if(positive(override))return{area:+override,version:'rooms-2026-10-06-v1',source:'User area override',needsConfirmation:false};let area=0;for(const[k,v]of Object.entries(rooms))area+=(ROOMS[k]||0)*Math.max(0,+v||0);return{area:area||null,version:'rooms-2026-10-06-v1',source:'Room allowances including circulation within each allowance',needsConfirmation:!area||!!rooms.other}}
function moveComparison(i={}){if(!i.enabled)return null;if(!positive(i.sale)||!positive(i.purchase)||!numeric(i.duty))return{status:'review',reason:'Confirm expected sale value, replacement price and applicable stamp duty.'};const selling=i.sale*(i.sellingPct??.025),other=(i.marketing??10000)+(i.legal??5000)+(i.moving??5000)+(i.finance??0),net=i.sale-selling,change=i.purchase+i.duty+other-net;return{status:'indicative',sale:i.sale,target:i.purchase,selling,net,duty:i.duty,other,change,assumptions:i}}
function parseMoney(v){const s=String(v??'').replace(/[$,\s]/g,'');return /^\d+$/.test(s)?+s:null}
function formatMoney(v){return numeric(v)?new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(+v):''}
function frontage(g,roads=[],primaryRoad=''){const unresolved={status:'review',label:'Indicative mapped frontage',primary:null,secondary:[],reason:'Parcel boundaries and road-facing geometry need confirmation.'};if(!g?.rings?.length||!roads.length)return unresolved;const geographic=!g.spatialReference||[4283,4326,7844].includes(g.spatialReference.wkid),origin=g.rings[0][0],cos=Math.cos(origin[1]*Math.PI/180),xy=p=>geographic?[(p[0]-origin[0])*111320*cos,(p[1]-origin[1])*111320]:p;
 const dist=(p,a,b)=>{const d=[b[0]-a[0],b[1]-a[1]],l=d[0]**2+d[1]**2,t=l?Math.max(0,Math.min(1,((p[0]-a[0])*d[0]+(p[1]-a[1])*d[1])/l)):0;return Math.hypot(p[0]-a[0]-t*d[0],p[1]-a[1]-t*d[1])},edges=new Map(),key=p=>p.map(n=>n.toFixed(3)).join(',');
 for(const ring of g.rings){for(let k=0;k<ring.length-1;k++){const a=xy(ring[k]),b=xy(ring[k+1]),id=[key(a),key(b)].sort().join('|');if(edges.has(id))edges.get(id).count++;else edges.set(id,{a,b,count:1})}}
 const candidates=new Map();for(const e of edges.values()){if(e.count!==1)continue;const length=Math.hypot(e.b[0]-e.a[0],e.b[1]-e.a[1]);if(length<1)continue;const mid=[(e.a[0]+e.b[0])/2,(e.a[1]+e.b[1])/2];let best=null;for(const road of roads){for(const path of road.paths||[]){for(let k=0;k<path.length-1;k++){const a=xy(path[k]),b=xy(path[k+1]),rl=Math.hypot(b[0]-a[0],b[1]-a[1]);if(!rl)continue;const align=Math.abs(((e.b[0]-e.a[0])*(b[0]-a[0])+(e.b[1]-e.a[1])*(b[1]-a[1]))/length/rl),distance=dist(mid,a,b);if(align<.94||distance>25||dist(e.a,a,b)>30||dist(e.b,a,b)>30)continue;if(!best||distance<best.distance)best={road,distance}}}}if(best){const id=best.road.id||best.road.name;if(!id)continue;const prev=candidates.get(id)||{road:best.road.name||String(id),metres:0,distance:best.distance};prev.metres+=length;prev.distance=Math.min(prev.distance,best.distance);candidates.set(id,prev)}}
 const rows=[...candidates.values()].sort((a,b)=>a.distance-b.distance);if(!rows.length)return unresolved;const name=primaryRoad.toUpperCase(),idx=rows.findIndex(r=>name&&r.road.toUpperCase().includes(name));const primary=rows.splice(idx>=0?idx:0,1)[0];const clean=r=>({...r,metres:Math.round(r.metres*10)/10});return{status:'indicative',label:'Indicative mapped frontage',primary:clean(primary),secondary:rows.map(clean),version:'road-facing-2026-10-06-v1',note:'Derived from cadastral boundary segments parallel and near mapped roads. Setbacks, road reserves and irregular/shared boundaries can affect this estimate; a registered survey is the legal authority.'}}
// One normalized profile for typed intake, speech transcripts and structured providers.
const RENOVATION_LABELS={kitchen:'Kitchen',bathroom:'Bathroom',living:'Living / dining',openplan:'Open up the floorplan',laundry:'Laundry',flooring:'Flooring / finishes',windows:'Windows / doors',office:'Home office / internal room conversion',outdoor:'Outdoor / alfresco',wholehome:'Whole-home renovation',other:'Other'};
function normalizeIntent(p={}){return{goal:p.goal||'unsure',rooms:p.rooms||{},desiredRooms:p.desiredRooms||[],renovationAreas:p.renovationAreas||[],extraBedrooms:p.extraBedrooms??null,extraBathrooms:p.extraBathrooms??null,moreLivingSpace:p.moreLivingSpace??null,renovationExtent:p.renovationExtent||null,additionalLevel:p.additionalLevel??null,developmentIntent:p.developmentIntent??null,developmentType:p.developmentType||null,dwellingCount:p.dwellingCount??null,basementPreference:p.basementPreference||'none',quality:p.quality||'premium',budget:p.budget??null,timeframe:p.timeframe||null,compareMove:!!p.compareMove,uncertainties:p.uncertainties||[]}}
function interpretIntent(text){
 const raw=String(text||'').toLowerCase().replace(/[’']/g,"'");
 // Exclude only the negated clause; keep independent positive requests.
 const t=raw.replace(/\b(?:do not|don't|not interested in|no|without|not)\s+(?:want\s+)?(?:to\s+)?(?:build\s+)?[^,.!?;]*(?=[,.!?;]|$)/g,' ');
 const p=normalizeIntent(),has=r=>r.test(t),counts={one:1,a:1,an:1,two:2,three:3,four:4,five:5,six:6};
 const count=r=>{const m=t.match(new RegExp('(?:\\b(\\d+|one|two|three|four|five|six)\\s+)?'+r,'i'));return m?Math.min(20,counts[m[1]]||+m[1]||1):0};
 const roomPatterns={bedroom:'bedrooms?',masterSuite:'master suite|main suite',bathroom:'bathrooms?|ensuite',living:'living(?: room| area)?|dining',kitchenLiving:'kitchen',office:'office|study',garage:'garage',laundry:'laundry',upperLevel:'full upper level|whole upstairs',other:'other room'};
 for(const[k,r]of Object.entries(roomPatterns)){const n=count(r);if(n)p.rooms[k]=n}
 const devCandidate=[['duplex',/duplex|dual occupancy/],['townhouse',/town\s*houses?|terraces/],['apartment',/apartments?|units/],['multisite',/neighbou?rs?|adjoining land|combine.*land/]].find(([,r])=>has(r));
 const existingHome=has(/(?:my|our|current|existing|the)\s+(?:apartment|duplex|townhouse)/)&&has(/renovat|improv|refresh|remodel|refurb/),newHomes=has(/(?:build|construct|create|develop)\s+(?:a\s+|an\s+|new\s+|some\s+)?(?:duplex|townhouses?|apartments?)|new (?:duplex|townhouses?|apartments?)/),dev=existingHome&&!newHomes?null:devCandidate;
 const storey=has(/upstairs|another (?:level|floor)|second (?:storey|story|floor)|upper (?:level|floor)|add.*(?:storey|story)/);
 const extend=has(/\bextend|extension|\badd(?:ing)?\s+(?:an?\s+|\d+\s+|one\s+|two\s+|three\s+)?(?:extra\s+)?(?:bedroom|bathroom|room|garage)|\bextra (?:bedroom|bathroom|space)|additional (?:room|space)/);
 const renovate=has(/renovat|refurb|refresh|improv|remodel|open.?plan|open up|knock.*wall|remove.*wall|internal.*(?:layout|convert)/);
 p.goal=dev||has(/\bdevelop(?:ment)?\b/)?'develop':storey?'storey':extend?'extend':renovate||Object.keys(p.rooms).length?'reno':'unsure';
 p.developmentType=dev?.[0]||null;p.developmentIntent=p.goal==='develop'?true:null;p.additionalLevel=storey?true:null;
 const areaPatterns={kitchen:/kitchen/,bathroom:/bathroom|ensuite/,living:/living|dining/,openplan:/open.?plan|open up|walls?|internal.*layout/,laundry:/laundry/,flooring:/flooring|finishes|carpet|tiles/,windows:/windows?|doors?/,office:/office|study|room conversion/,outdoor:/outdoor|alfresco|deck/,wholehome:/whole.?home|whole house/};
 p.renovationAreas=p.goal==='reno'?Object.entries(areaPatterns).filter(([,r])=>has(r)).map(([k])=>k):[];
 if(p.goal==='reno'&&p.renovationAreas.includes('flooring')&&p.renovationAreas.some(k=>['bathroom','kitchen','living','office','laundry'].includes(k))&&!has(/elsewhere|other rooms|throughout|whole (?:home|house)|(?:living|bedroom|hall).*floor|flooring (?:through|across|in other)/))p.renovationAreas=p.renovationAreas.filter(k=>k!=='flooring');
 const unsupported=t.match(/\b(?:pool|roof(?:ing)?|solar panels?|lift|fence|retaining wall|foundation|air conditioning|asbestos)\b/g)||[];if(p.goal==='reno'&&unsupported.length){p.renovationAreas.push('other');p.uncertainties.push('Also requested: '+[...new Set(unsupported)].join(', ')+'. This needs a separate scope and price.')}
 p.renovationExtent=has(/major structural/)?'structural':p.renovationAreas.includes('openplan')?'layout':has(/refresh|cosmetic|paint/)?'refresh':'replace';
 p.extraBedrooms=p.goal==='extend'||p.goal==='storey'?p.rooms.bedroom||null:null;p.extraBathrooms=p.goal==='extend'||p.goal==='storey'?p.rooms.bathroom||null:null;p.moreLivingSpace=has(/living.*(?:bigger|larger)|more living/)?true:null;
 p.basementPreference=has(/basement/)?'basement':'none';p.quality=has(/luxury|bespoke|high.end/)?'luxury':has(/standard|basic|budget finish/)?'standard':'premium';p.compareMove=has(/mov(?:e|ing)|sell|buy elsewhere|compare.*alternatives/);
 const money=t.match(/(?:budget\s*(?:of|is|around|about)?\s*|\$)(\d[\d,]*(?:\.\d+)?)\s*(million|thousand|m\b|k\b)?/);if(money)p.budget=Math.round(+money[1].replace(/,/g,'')*(/million|m\b/.test(money[2]||'')?1e6:/thousand|k\b/.test(money[2]||'')?1e3:1));
 const words=t.match(/budget\s+(one|two|three|four|five|six|seven|eight|nine)\s+hundred\s+thousand/);if(words)p.budget=({one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9}[words[1]])*100000;
 p.desiredRooms=Object.keys(p.rooms);if(p.goal==='develop'&&p.developmentType==='duplex')p.dwellingCount=2;
 const footprintConstraint=/not extend|no extension|without extend|within (?:the )?existing footprint/.test(raw),mixed=renovate&&(extend||storey||dev)||(extend&&!!dev)||(storey&&!!dev)||(extend&&storey),unclear=mixed||footprintConstraint||unsupported.length;const confidence=unclear?.55:p.goal==='unsure'?.25:renovate||extend||storey||dev?.9:.65;
 return{status:'confirmation',profile:p,confidence,clarification:unsupported.length?'Should we include '+[...new Set(unsupported)].join(' and ')+' as work that still needs a separate price?':footprintConstraint?'Are you converting space inside the existing home rather than extending it?':mixed?'Which direction would you like to test first: improving existing rooms, adding space, or building new homes?':confidence<.7?'Are you improving the existing rooms, adding space, or building additional homes?':null};
}
// Founder component assumptions: GST, ordinary installation, local services and 10% room contingency included.
// These are NOT verified quotes. Houzz AU 2023 median kitchen $30k/bath $19k is historical context only.
const RENO_VERSION='renovation-components-2026-10-07-v1';
const RENOVATION_COMPONENTS={
 kitchen:{label:'Kitchen',band:[25000,40000,65000],includes:['Cabinetry, benchtop, standard appliances','Room electrical/plumbing, finishes and installation']},
 bathroom:{label:'Bathroom',band:[18000,28000,45000],includes:['Fixtures, waterproofing, tiling','Room electrical/plumbing and installation']},
 openplan:{label:'Open-plan structural changes',band:[12000,22000,40000],includes:['One internal structural opening','Engineering allowance, beam and making good']},
 living:{label:'Living / dining refurbishment',band:[5000,10000,18000],includes:['Room painting, basic flooring and local electrical']},
 flooring:{label:'Flooring / finishes elsewhere',band:[7000,12000,22000],includes:['Shared dry-room flooring outside selected rooms']},
 joinery:{label:'Additional joinery',band:[5000,10000,20000],includes:['Joinery outside kitchen and bathroom']},
 painting:{label:'Painting elsewhere',band:[5000,9000,16000],includes:['Shared interior painting outside selected rooms']},
 electrical:{label:'Additional electrical work',band:[3000,6500,12000],includes:['Electrical upgrades outside selected rooms']},
 plumbing:{label:'Additional plumbing work',band:[3000,6000,12000],includes:['Plumbing upgrades outside selected rooms']},
 windows:{label:'Windows / doors',band:[7000,15000,28000],includes:['Small group of replacement windows or doors']},
 office:{label:'Office conversion',band:[4000,8000,14000],includes:['Existing-room finishes, lighting and desk joinery']},
 laundry:{label:'Laundry',band:[8000,15000,25000],includes:['Cabinetry, fixtures and local plumbing/electrical']},
 wholehome:{label:'Whole-home shared finishes',band:[30000,55000,95000],includes:['Shared dry-room finishes, flooring, painting and ordinary electrical','Excludes separately selected kitchen, bathroom and structural work']},
 outdoor:{label:'Outdoor / alfresco improvement',band:[10000,22000,40000],includes:['Modest existing outdoor area finishes and connection']}
};
function renovationCost({components=[],extent='replace',quality='premium',complexity='normal',region=1,counts={}}={}){
 const unique=[...new Set(components)],unknown=unique.some(k=>!RENOVATION_COMPONENTS[k]);const keys=unique.filter(k=>RENOVATION_COMPONENTS[k]&&!(unique.includes('wholehome')&&['flooring','painting','electrical','living','office'].includes(k)));
 if(!keys.length||unknown)return{status:'review',low:null,mid:null,high:null,reason:'Describe the additional work so a designer or builder can price it.',version:RENO_VERSION,components:[]};
 const qualityAdjustment={standard:1,premium:1.2,luxury:1.6}[quality]||1.2,complexityAdjustment={simple:.95,normal:1,hard:1.2}[complexity]||1,regionAdjustment=positive(region)?+region:1;
 const lines=keys.map(k=>{const c=RENOVATION_COMPONENTS[k],extentAdjustment=k==='openplan'?1:extent==='refresh'?.55:extent==='structural'?1.25:1,n=Math.max(1,Math.min(20,+counts[k]||1)),factor=qualityAdjustment*complexityAdjustment*regionAdjustment*extentAdjustment*n;return{key:k,label:c.label,low:Math.round(c.band[0]*factor),mid:Math.round(c.band[1]*factor),high:Math.round(c.band[2]*factor),count:n,qualityAdjustment,complexityAdjustment,regionAdjustment,extentAdjustment,version:RENO_VERSION,inclusions:[...c.includes,'GST and ordinary room contingency'],exclusions:['Extensions or additional levels','Major service relocation, hazardous materials or exceptional structure','Unselected rooms, furnishings and temporary accommodation']}});
 return{status:'indicative',low:lines.reduce((n,c)=>n+c.low,0),mid:lines.reduce((n,c)=>n+c.mid,0),high:lines.reduce((n,c)=>n+c.high,0),components:lines,version:RENO_VERSION,qualityAdjustment,complexityAdjustment,regionAdjustment,note:'Selected room allowances include ordinary installation, services, GST and room contingency. These working estimates need a measured scope and builder pricing; exceptional work is excluded.'};
}
function deliveryComposition(cost){if(!positive(cost?.mid))return[];const shares=[['Main building work',.72],['Design and consultants',.1],['Approvals and reports',.03],['Site works',.05],['Construction contingency',.1]];let used=0;return shares.map(([label,share],k)=>{const amount=k===shares.length-1?cost.mid-used:Math.round(cost.mid*share);used+=amount;return{label,amount,share,version:'delivered-composition-2026-10-07-v1',source:'Illustrative allocation of the delivered total; not additional costs'}})}

return{interpretIntent,normalizeIntent,RENOVATION_LABELS,RENOVATION_COMPONENTS,renovationCost,deliveryComposition,rateCard,deliveredCost,feasibility,roomArea,ROOMS,moveComparison,parseMoney,formatMoney,frontage};});
