/* Shared browser/server arithmetic. Values are indicative versioned assumptions, not quotes. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.SitePivotCommercial=factory()})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const VERSION='delivered-2026-10-06-v1',ROOMS={bedroom:14,masterSuite:30,bathroom:10,living:30,kitchenLiving:40,office:10,garage:36,upperLevel:100,other:0};
const numeric=n=>n!==null&&n!==''&&n!==undefined&&Number.isFinite(+n),positive=n=>numeric(n)&&+n>0;
function rateCard({quality='premium',configuration='two-storey',region='NSW',customRate}={}){const bands={standard:[4800,5600,6500],premium:[6000,6800,8000],luxury:[9200,10500,11800]},configs={'two-storey':[0,0,0],'two-storey-basement':[800,1200,1800],'three-level-basement':[1000,1500,2200]},b=bands[quality]||bands.premium,add=configs[configuration];if(!add&&!(configuration==='custom'&&positive(customRate)))return{status:'review',reason:'A custom configuration needs an explicit QS/builder delivered rate.'};const r=configuration==='custom'?[+customRate,+customRate,+customRate]:b.map((n,i)=>n+add[i]);return{status:'indicative',rateLow:r[0],rateMid:r[1],rateHigh:r[2],includedCosts:['construction','professional','approvals','externalWorks','contingency'],excludedCosts:['land','demolition','authorityContributions','finance','holding','selling','marketing','legal','taxSensitivity'],configuration,region,quality,version:VERSION,taxBasis:'Construction GST included; project GST/tax needs a separate accountant-approved net adjustment.',note:'Delivered rate includes construction, ordinary design/professional fees, approvals/reports, external works and construction contingency. Exceptional ground conditions, contributions, demolition and commercial costs need explicit confirmation. Basement premiums are indicative configuration assumptions.'}}
function deliveredCost(input={}){const r=input.rateCard||rateCard(input);if(r.status==='review'||!positive(input.area))return{...r,status:'review',low:null,mid:null,high:null,reason:r.reason||'Confirm total constructed area.'};return{...r,area:+input.area,low:+input.area*r.rateLow,mid:+input.area*r.rateMid,high:+input.area*r.rateHigh,constructionLow:+input.area*r.rateLow,constructionHigh:+input.area*r.rateHigh,professionalPct:0,approvalsPct:0,externalPct:0,contingencyPct:0,demolition:0,complexity:1}}
function feasibility(i={}){if(!positive(i.land)||!positive(i.cost?.mid)||!i.products?.length||i.products.some(p=>!positive(p.value)||!Number.isInteger(+p.count)||+p.count<1))return{status:'review',reason:'Confirm land/current-property value, delivered cost and sold evidence or explicit user assumptions for each finished product.'};const grv=i.products.reduce((a,p)=>a+p.value*p.count,0),land=+i.land,delivery=i.cost.mid,lines={};for(const [key,val]of Object.entries(i.extras||{})){if(['demolition','professional','approvals','externalWorks','contingency','authorityContributions'].includes(key)&&(i.cost.excludedCosts||[]).includes(key)&&numeric(val)&&+val>=0)lines[key]=+val}
 const extras=Object.values(lines).reduce((a,b)=>a+b,0),years=(i.holdingMonths??18)/12,interest=i.interestRate??.07,landDebt=i.landDebtRatio??.7,draw=i.constructionDrawdown??.5,finance=(land*landDebt+(delivery+extras)*draw)*interest*years,establishment=i.financeEstablishment??20000,holding=i.holding??15000,selling=grv*(i.sellingPct??.025),marketing=i.marketing??10000,legal=i.legal??30000,taxSensitivity=grv*(i.taxPct??.04),nonLand=delivery+extras+(delivery+extras)*draw*interest*years+establishment+holding+selling+marketing+legal+taxSensitivity,landFactor=1+landDebt*interest*years,total=land+delivery+extras+finance+establishment+holding+selling+marketing+legal+taxSensitivity,profit=grv-total,target=i.targetProfitOnCost??.2,residual=(grv/(1+target)-nonLand)/landFactor;
 return{status:'indicative',grv,site:land,delivery,lines,finance,financeEstablishment:establishment,holding,selling,marketing,legal,taxSensitivity,total,profit,margin:profit,profitOnCost:profit/total,profitOnGrv:profit/grv,marginPct:profit/grv,residualLandValue:residual,holdingMonths:years*12,interestRate:interest,targetProfitOnCost:target,assumptions:{landDebtRatio:landDebt,constructionDrawdown:draw},note:'Simple staged drawdown sensitivity; financing terms, timing, excluded allowances and net GST/tax adjustment require professional confirmation. Residual assumes retained existing land (no acquisition duty), fixed construction costs and the stated target profit on cost.'}}
function roomArea(rooms={},override){if(positive(override))return{area:+override,version:'rooms-2026-10-06-v1',source:'User area override',needsConfirmation:false};let area=0;for(const[k,v]of Object.entries(rooms))area+=(ROOMS[k]||0)*Math.max(0,+v||0);return{area:area||null,version:'rooms-2026-10-06-v1',source:'Room allowances including circulation within each allowance',needsConfirmation:!area||!!rooms.other}}
function moveComparison(i={}){if(!i.enabled)return null;if(!positive(i.sale)||!positive(i.purchase)||!numeric(i.duty))return{status:'review',reason:'Confirm expected sale value, replacement price and applicable stamp duty.'};const selling=i.sale*(i.sellingPct??.025),other=(i.marketing??10000)+(i.legal??5000)+(i.moving??5000)+(i.finance??0),net=i.sale-selling,change=i.purchase+i.duty+other-net;return{status:'indicative',sale:i.sale,target:i.purchase,selling,net,duty:i.duty,other,change,assumptions:i}}
function parseMoney(v){const s=String(v??'').replace(/[$,\s]/g,'');return /^\d+$/.test(s)?+s:null}
function formatMoney(v){return numeric(v)?new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(+v):''}
function frontage(g,roads=[],primaryRoad=''){const unresolved={status:'review',label:'Indicative mapped frontage',primary:null,secondary:[],reason:'Parcel boundaries and road-facing geometry need confirmation.'};if(!g?.rings?.length||!roads.length)return unresolved;const geographic=!g.spatialReference||[4283,4326,7844].includes(g.spatialReference.wkid),origin=g.rings[0][0],cos=Math.cos(origin[1]*Math.PI/180),xy=p=>geographic?[(p[0]-origin[0])*111320*cos,(p[1]-origin[1])*111320]:p;
 const dist=(p,a,b)=>{const d=[b[0]-a[0],b[1]-a[1]],l=d[0]**2+d[1]**2,t=l?Math.max(0,Math.min(1,((p[0]-a[0])*d[0]+(p[1]-a[1])*d[1])/l)):0;return Math.hypot(p[0]-a[0]-t*d[0],p[1]-a[1]-t*d[1])},edges=new Map(),key=p=>p.map(n=>n.toFixed(3)).join(',');
 for(const ring of g.rings){for(let k=0;k<ring.length-1;k++){const a=xy(ring[k]),b=xy(ring[k+1]),id=[key(a),key(b)].sort().join('|');if(edges.has(id))edges.get(id).count++;else edges.set(id,{a,b,count:1})}}
 const candidates=new Map();for(const e of edges.values()){if(e.count!==1)continue;const length=Math.hypot(e.b[0]-e.a[0],e.b[1]-e.a[1]);if(length<1)continue;const mid=[(e.a[0]+e.b[0])/2,(e.a[1]+e.b[1])/2];let best=null;for(const road of roads){for(const path of road.paths||[]){for(let k=0;k<path.length-1;k++){const a=xy(path[k]),b=xy(path[k+1]),rl=Math.hypot(b[0]-a[0],b[1]-a[1]);if(!rl)continue;const align=Math.abs(((e.b[0]-e.a[0])*(b[0]-a[0])+(e.b[1]-e.a[1])*(b[1]-a[1]))/length/rl),distance=dist(mid,a,b);if(align<.94||distance>25||dist(e.a,a,b)>30||dist(e.b,a,b)>30)continue;if(!best||distance<best.distance)best={road,distance}}}}if(best){const id=best.road.id||best.road.name;if(!id)continue;const prev=candidates.get(id)||{road:best.road.name||String(id),metres:0,distance:best.distance};prev.metres+=length;prev.distance=Math.min(prev.distance,best.distance);candidates.set(id,prev)}}
 const rows=[...candidates.values()].sort((a,b)=>a.distance-b.distance);if(!rows.length)return unresolved;const name=primaryRoad.toUpperCase(),idx=rows.findIndex(r=>name&&r.road.toUpperCase().includes(name));const primary=rows.splice(idx>=0?idx:0,1)[0];const clean=r=>({...r,metres:Math.round(r.metres*10)/10});return{status:'indicative',label:'Indicative mapped frontage',primary:clean(primary),secondary:rows.map(clean),version:'road-facing-2026-10-06-v1',note:'Derived from cadastral boundary segments parallel and near mapped roads. Setbacks, road reserves and irregular/shared boundaries can affect this estimate; a registered survey is the legal authority.'}}
return{rateCard,deliveredCost,feasibility,roomArea,ROOMS,moveComparison,parseMoney,formatMoney,frontage};});
