(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./commercial-engine.js'));else root.SitePivotConversation=factory(root.SitePivotCommercial)})(typeof globalThis!=='undefined'?globalThis:this,function(E){'use strict';
const GOALS=['reno','extend','storey','develop','unsure'],DEV=['duplex','townhouse','apartment','multisite','unsure'],ROOMS=Object.keys(E.ROOMS),COMP=Object.keys(E.RENOVATION_LABELS),FORMS=['two-storey','two-storey-basement','three-level-basement','custom'];
const questions={heritage:/heritage/i,area:/land area|site area|how big|size of.*(?:land|site)/i,council:/council|\blga\b/i,bushfire:/bush.?fire/i,minlot:/minimum lot|min lot/i,identity:/cadastral|parcel|title|which property|address|\bdp\b/i,environment:/environment|biodiversity|riparian|watercourse|wetland|landslide/i,sepp:/\bsepp\b|state environmental/i,contributions:/contribution/i,improvement:/improve.*result|improve.*margin/i,approval:/approval|need.*(?:permission|consent)/i,structural:/wall.*structural|structural.*wall/i,planning:/planning controls|controls are|controls apply|what controls|local rules/i,zoning:/\bzon(?:e|ing)\b/i,height:/height/i,fsr:/\bfsr\b|floor space/i,frontage:/frontage/i,flood:/flood/i,acid:/acid sulfate/i,dcp:/\bdcp\b|development control plan/i,duplex:/duplex|dual occupancy/i,checks:/what.*stop|worried|risk|constraint|check|red flag/i,cost:/cost|how much|roughly cost/i,value:/value|worth|market/i,feasibility:/feasib|profit|margin/i,next:/who should|next step|speak to|what should i do/i,evidence:/evidence|source/i,storey:/could.*(?:level|upstairs)|can.*another level/i,options:/what could|what can|possible/i};
function normalize(p={}){return{primaryPathway:GOALS.includes(p.primaryPathway)?p.primaryPathway:null,developmentType:DEV.includes(p.developmentType)?p.developmentType:null,projectComponents:Array.isArray(p.projectComponents)?p.projectComponents.filter(x=>COMP.includes(x)):[],rooms:Object.fromEntries(Object.entries(p.rooms||{}).filter(([k,v])=>ROOMS.includes(k)&&Number.isInteger(v)&&v>0&&v<=20)),renovationType:['refresh','replace','layout','structural'].includes(p.renovationType)?p.renovationType:null,structuralIntent:p.structuralIntent==='possible'?'possible':null,additionalArea:Number.isFinite(p.additionalArea)&&p.additionalArea>0?p.additionalArea:null,additionalLevel:typeof p.additionalLevel==='boolean'?p.additionalLevel:null,builtForm:FORMS.includes(p.builtForm)?p.builtForm:null,basement:typeof p.basement==='boolean'?p.basement:null,dwellingCount:Number.isInteger(p.dwellingCount)&&p.dwellingCount>0&&p.dwellingCount<=100?p.dwellingCount:null,budget:Number.isFinite(p.budget)&&p.budget>0&&p.budget<=1e9?Math.round(p.budget):null,quality:['standard','premium','luxury'].includes(p.quality)?p.quality:null,moveComparisonInterest:typeof p.moveComparisonInterest==='boolean'?p.moveComparisonInterest:null,timeframe:typeof p.timeframe==='string'?p.timeframe.slice(0,100):null,questions:Array.isArray(p.questions)?p.questions.filter(k=>k in questions):[],confidence:Math.max(0,Math.min(1,+p.confidence||0)),unresolvedItems:Array.isArray(p.unresolvedItems)?p.unresolvedItems.filter(x=>typeof x==='string').slice(0,10):[],candidatePathways:Array.isArray(p.candidatePathways)?p.candidatePathways.filter(k=>GOALS.includes(k)):[]}}
function actionsFor(i){const a=[],add=(type,value)=>a.push({type,value});if(i.primaryPathway)add('setPrimaryPathway',i.primaryPathway);if(i.developmentType)add('setDevelopmentType',i.developmentType);if(i.projectComponents.length)add('setRenovationScope',i.projectComponents);if(Object.keys(i.rooms).length)add('setRooms',i.rooms);if(i.budget!=null)add('setBudget',i.budget);if(i.quality)add('setQuality',i.quality);if(i.renovationType)add('setRenovationType',i.renovationType);if(i.builtForm)add('setBuiltForm',i.builtForm);if(i.dwellingCount)add('setDwellingCount',i.dwellingCount);if(i.moveComparisonInterest!=null)add('setMoveComparison',i.moveComparisonInterest);for(const q of i.questions)add(q==='planning'?'answerPlanningQuestion':'answerPropertyQuestion',q);return a}
function interpret(text,context={}){const t=String(text||'').trim(),l=t.toLowerCase(),r=E.interpretIntent(t),p=r.profile;let qs=Object.entries(questions).filter(([,rx])=>rx.test(t)).map(([k])=>k);
 const queryOnly=/^(?:what|how|who|is|are|does|which)\b/i.test(t)&&qs.length>0&&!/\b(?:i want|i would like|i’m thinking|i am thinking|we want|let.s explore)\b/i.test(t);
 const project=(!queryOnly||qs.includes('duplex'))&&/renovat|improv|refurb|extend|extension|upstairs|another (?:level|bedroom)|duplex|dual occupancy|townhouse|apartment|develop|open up|open.?plan|more room|extra (?:bedroom|bathroom)|add.*(?:bedroom|space)/i.test(t);let goal=project&&p.goal!=='unsure'?p.goal:null;
 if(/(?:my|our|existing|current)\s+(?:apartment|duplex|townhouse)/i.test(t)&&/renovat|improv/i.test(t)){goal='reno';qs=qs.filter(q=>q!=='duplex')}
 const compare=/extend/.test(l)&&/upstairs|another level/.test(l)&&/or|whether|not sure/.test(l),moreRoom=/more room|more space/.test(l)&&!Object.keys(p.rooms).length;
 let clarification=compare?'We can compare extending out and adding a level for the extra bedroom. Would you prefer to keep the garden, or avoid work upstairs?':moreRoom?'What would help most — another bedroom, a larger living area, or both?':project&&r.confidence<.7?r.clarification:null;
 if(compare||moreRoom)goal=null;
 const roomFollow=context.pendingQuestion==='more-room'&&/bedroom|living|both/.test(l);if(roomFollow){p.rooms={};if(/bedroom|both/.test(l))p.rooms.bedroom=1;if(/living|both/.test(l))p.rooms.living=1;clarification='Would you prefer to extend out, or explore adding a level?'}
 const budgetOnly=!goal&&p.budget!=null;const reno=!queryOnly&&(goal==='reno'||(!goal&&context.goal==='reno'&&/kitchen|bathroom|living|office|laundry|floor|open plan/.test(l)));
 if(context.pendingQuestion==='choose-route'&&goal&&['extend','storey'].includes(goal))p.rooms={...context.scope?.rooms,...p.rooms};
 const noBasement=/\b(?:no|without|not|remove)\s+(?:a\s+)?basement/.test(l);
 const i=normalize({primaryPathway:goal,developmentType:goal==='develop'?p.developmentType:null,projectComponents:reno?[...new Set([...(context.goal===goal||!goal?context.scope?.renovationAreas||[]:[]),...p.renovationAreas])]:[],rooms:project||roomFollow||reno?p.rooms:{},renovationType:reno?p.renovationExtent:null,structuralIntent:reno&&p.renovationAreas.includes('openplan')?'possible':null,additionalLevel:goal==='storey'?true:null,builtForm:noBasement?'two-storey':/3 levels|three levels/.test(l)?'three-level-basement':/basement/.test(l)?'two-storey-basement':/2 stor|two stor/.test(l)?'two-storey':null,basement:noBasement?false:/basement/.test(l)?true:null,dwellingCount:goal==='develop'?p.dwellingCount:null,budget:p.budget,quality:/luxury|standard|premium|basic|high.end/.test(l)?p.quality:null,moveComparisonInterest:/compare.*mov|sell|buy elsewhere/.test(l)?true:null,questions:qs,confidence:compare||moreRoom?.6:goal?r.confidence:qs.length||budgetOnly?.95:.3,unresolvedItems:clarification?[clarification]:[],candidatePathways:compare?['extend','storey']:[]});
 if(reno&&/remove|exclude|skip|without|no /.test(l)){const areas={kitchen:/kitchen/,bathroom:/bathroom/,living:/living|dining/,openplan:/open.?plan/,laundry:/laundry/,office:/office/};const remove=Object.entries(areas).filter(([,rx])=>rx.test(l)).map(([k])=>k);i.projectComponents=(context.scope?.renovationAreas||i.projectComponents).filter(k=>!remove.includes(k));}
 let response=clarification|| (goal==='reno'?'Got it. You’re mainly looking at '+(i.projectComponents.map(k=>E.RENOVATION_LABELS[k]).join(', ')||'improving your existing home')+'. I’ll treat this as an internal renovation for now.'+(i.structuralIntent?' If opening up the living space involves removing structural walls, we’ll allow for that separately.':''):goal==='develop'&&i.developmentType==='duplex'?'You’re looking at whether a duplex could work here. I’ve set Duplex as the option we’re exploring.':goal==='develop'?'I’ll explore '+(i.developmentType||'development')+' with you.':goal==='extend'?'I’ll explore an extension for the additional space you want.':goal==='storey'?'I’ll explore adding another level for the rooms you want.':budgetOnly?'I’ll use '+E.formatMoney(i.budget)+' as your working budget.':'');
 if(!response&&!qs.length)response='Are you mainly looking to renovate, add space, or develop the property?';
 const actions=actionsFor(i);if(reno&&/remove|exclude|skip|without|no /.test(l)&&!i.projectComponents.length)actions.push({type:'setRenovationScope',value:[]});if(/value|per dwelling|per home/.test(l)&&p.budget&&/working|current property|per dwelling|per home|land value|site value/.test(l)){const key=/per dwelling|per home|completed/.test(l)?'salePerDwelling':'landValue';actions.splice(0,actions.length,...actions.filter(a=>a.type!=='setBudget'),{type:'setWorkingValue',key,value:p.budget});i.budget=null;response='I’ll use '+E.formatMoney(p.budget)+' as your working '+(key==='landValue'?'property value.':'value per completed dwelling.');}
 return{response,intent:i,actions,confidence:i.confidence,clarification,pendingQuestion:moreRoom?'more-room':compare||roomFollow?'choose-route':null};}
function valid(a){if(!a||typeof a!=='object')return false;const v=a.value;switch(a.type){case'setPrimaryPathway':return GOALS.includes(v);case'setDevelopmentType':return DEV.includes(v);case'setRenovationScope':return Array.isArray(v)&&v.length<=COMP.length&&v.every(k=>COMP.includes(k));case'setRooms':return v&&typeof v==='object'&&!Array.isArray(v)&&Object.entries(v).every(([k,n])=>ROOMS.includes(k)&&Number.isInteger(n)&&n>0&&n<=20);case'setBudget':return Number.isFinite(v)&&v>0&&v<=1e9;case'setBuiltForm':return FORMS.includes(v);case'setDwellingCount':return Number.isInteger(v)&&v>0&&v<=100;case'setQuality':return['standard','premium','luxury'].includes(v);case'setRenovationType':return['refresh','replace','layout','structural'].includes(v);case'setMoveComparison':return typeof v==='boolean';case'setWorkingValue':return['landValue','salePerDwelling'].includes(a.key)&&Number.isFinite(v)&&v>0&&v<=1e9;case'answerPropertyQuestion':case'answerPlanningQuestion':return v in questions;case'requestClarification':return typeof v==='string'&&v.length<=500;case'navigateToScope':case'navigateToAssessment':case'showEvidence':return true;default:return false}}
function applyActions(state,actions){const s={...state,scope:{...state.scope,rooms:{...state.scope?.rooms},feasibility:{...state.scope?.feasibility}}},accepted=[],rejected=[];for(const a of Array.isArray(actions)?actions:[]){if(!valid(a)){rejected.push(a);continue}accepted.push(a);const v=a.value;switch(a.type){case'setPrimaryPathway':if(s.goal!==v){s.scope.rooms={};s.scope.renovationAreas=[];s.scope.area=null;s.devType=null}s.goal=v;break;case'setDevelopmentType':s.goal='develop';s.devType=v;break;case'setRenovationScope':s.scope.renovationAreas=[...new Set(v)];break;case'setRooms':s.scope.rooms={...s.scope.rooms,...v};if(s.goal==='extend'||s.goal==='storey')s.scope.area=E.roomArea(s.scope.rooms).area;s.scope.renovationCounts={bathroom:s.scope.rooms.bathroom||1};break;case'setBudget':s.scope.budget=Math.round(v);break;case'setQuality':s.scope.quality=v;break;case'setRenovationType':s.scope.renovationExtent=v;break;case'setBuiltForm':s.scope.configuration=v;break;case'setDwellingCount':s.scope.dwellings=v;break;case'setMoveComparison':s.scope.moveEnabled=v;break;case'setWorkingValue':s.scope[a.key]=Math.round(v);s.scope.feasibility[a.key]=Math.round(v);break;}}return{state:accepted.some(a=>a.type.startsWith('set'))?s:state,accepted,rejected}}
function describe(i){if(i.unresolvedItems?.length)return i.unresolvedItems[0];if(i.primaryPathway==='reno')return 'I’ll assess this as an internal renovation'+(i.projectComponents.length?' of '+i.projectComponents.map(k=>E.RENOVATION_LABELS[k]).join(', '):'')+'.';if(i.primaryPathway==='extend')return 'I’ll explore an extension for the extra space you want.';if(i.primaryPathway==='storey')return 'I’ll explore adding another level for the rooms you want.';if(i.primaryPathway==='develop')return 'I’ve set '+(i.developmentType==='duplex'?'Duplex':i.developmentType||'development')+' as the option we’re exploring. We’ll still check the property controls before calling it feasible.';if(i.budget)return 'I’ll use '+E.formatMoney(i.budget)+' as your working budget.';return ''}
 return{interpret,normalize,actionsFor,applyActions,valid,describe};});
