'use strict';
const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const out=path.join(__dirname,'../qa-artifacts/duplex');fs.mkdirSync(out,{recursive:true});
const live=!!process.env.SITEPIVOT_URL,server=live?null:require('./founder-server.cjs').createServer();
(async()=>{if(server)await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=process.env.SITEPIVOT_URL||`http://127.0.0.1:${server.address().port}/`,results=[];
for(const engine of [chromium,webkit]){const browser=await engine.launch();for(const width of [390,1280])for(const name of ['violet','nield','eileen']){const page=await browser.newPage({viewport:{width,height:width<500?844:900},isMobile:width<500,hasTouch:width<500}),errors=[];page.setDefaultTimeout(45000);page.on('pageerror',e=>errors.push(e.message));const capture=require('./fixtures/zoning-evidence/'+name+'.json'),address=capture.address.response.features[0].attributes.formattedaddress;
try{await page.goto(base);if(live){await page.locator('#addressSearch').fill(address);await page.locator('[data-live-index]').first().click();await page.locator('#confirmProperty').click();await page.locator('#saveDwellingProfile').waitFor();for(const[id,n]of [['confirmBeds','3'],['confirmBaths','2'],['confirmCars','1']])await page.locator('#'+id).fill(n);await page.locator('#saveDwellingProfile').click();await page.waitForFunction(()=>SitePivot.app.property&&!SitePivot.app.property.planning.loading);}else await page.evaluate(({capture,name})=>{const a=SitePivot,p=JSON.parse(JSON.stringify(a.FIXTURES[0])),at=capture.address.response.features[0].attributes,parcel=capture.parcel.response.features[0],geometry={...parcel.geometry,spatialReference:capture.parcel.response.spatialReference},ze=SitePivotZoning.resolve({records:capture.zone.response.features.map(f=>({...f,geometry:{...f.geometry,spatialReference:capture.zone.response.spatialReference}})),parcelGeometry:geometry,source:capture.zone.url,checkedAt:capture.zone.checkedAt});Object.assign(p,{address:at.formattedaddress,area:PropertyEvidence.geometryArea(geometry),frontage:name==='violet'?13:name==='nield'?15.9:13,lot:parcel.attributes.lotnumber,dp:parcel.attributes.planlabel});p.planning={...p.planning,zone:ze.primaryZone.label,instrument:ze.primaryZone.instrument,zoningEvidence:ze,splitZone:ze.splitZone,fsr:name==='eileen'?null:'0.5:1'};a.selectProperty(p);a.show('passport')},{capture,name});
const property=await page.evaluate(()=>{const p=SitePivot.app.property;return{address:p.address,area:p.area,frontage:p.frontage,lot:p.lot,dp:p.dp,zone:p.planning.zone,instrument:p.planning.instrument,zoning:p.planning.zoningEvidence,fsr:p.planning.fsr}});assert.match(property.address,new RegExp(name==='violet'?'VIOLET':name==='nield'?'NIELD':'EILEEN','i'));assert.ok(Math.abs(property.area-({violet:596.8016,nield:605.9145,eileen:471.3665}[name]))<.3);
async function say(t){await page.locator('#assistantInput').fill(t);await page.locator('#assistantSend').click();return page.locator('#assistantMessages .assistant').last().innerText()}
const reply=await say('Could I build a duplex here?');if(name==='eileen'){assert.match(reply,/471.4.*800/s);assert.equal(await page.locator('#confirmIntent').count(),0);assert.equal(await page.evaluate(()=>SitePivot.computeAssessment().cost.mid),null);}else{assert.match(property.zone,/^R1/);assert.match(property.instrument,/^Manly Local Environmental Plan 2013$/);assert.match(reply,/conditional DA opportunity/);assert.equal(await page.locator('#confirmIntent').innerText(),'Explore duplex costs');const cdc=await say('Could I use complying development CDC here?');assert.match(cdc,/surveyed width at the building line/);assert.match(cdc,new RegExp(name==='violet'?'13':'15.9'));assert.doesNotMatch(cdc,/CDC approved|CDC approval confirmed/);await page.locator('#confirmIntent').click();assert.match(await page.locator('#developmentPathwayNotice').innerText(),/Conditional/);assert.match(await page.locator('#developmentPathwayNotice').innerText(),/statutory floor area/);
// Explicit scenario assumptions, not market evidence or a lender quotation.
await page.evaluate(()=>{const a=SitePivot;Object.assign(a.app.scope,{gfa:300,dwellings:2,landValue:2000000,salePerDwelling:2500000,landDebt:800000,contributions:25000});a.computeAssessment();a.show('assessment')});const scenario=await page.evaluate(()=>({cost:SitePivot.app.assessment.cost.status,feas:SitePivot.app.assessment.feas.status,decisionReady:SitePivot.app.assessment.feas.decisionReady}));assert.equal(scenario.cost,'conditional');assert.equal(scenario.feas,'conditional');assert.equal(scenario.decisionReady,false);assert.match(await page.locator('#consumerResult').innerText(),/Conditional scenario/);assert.ok(await page.locator('#compareAlternatives').isHidden());}
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow');assert.deepEqual(errors,[]);await page.screenshot({path:path.join(out,`${engine.name()}-${width}-${name}.png`),fullPage:true});results.push({engine:engine.name(),width,name,live,pass:true,property,reply});console.log(`PASS duplex ${engine.name()} ${width} ${name} ${live?'live official data':'captured official geometry'}`);
}catch(e){results.push({engine:engine.name(),width,name,live,pass:false,error:e.stack,pageErrors:errors});console.error(e.stack);await page.screenshot({path:path.join(out,`${engine.name()}-${width}-${name}-failure.png`),fullPage:true}).catch(()=>{});}finally{await page.close()}}await browser.close()}
fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));if(server)server.close();process.exitCode=results.some(r=>!r.pass)?1:0;})().catch(e=>{console.error(e);if(server)server.close();process.exitCode=1});
