'use strict';
const {webkit}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const server=http.createServer((req,res)=>{const file=['/commercial-engine.js','/conversation.js','/voice.js'].includes(req.url.split('?')[0])?req.url.split('?')[0].slice(1):'index.html';res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':'text/html');res.end(fs.readFileSync(path.join(__dirname,'..',file)))});
const results=[];
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await webkit.launch();fs.mkdirSync('mobile-qa',{recursive:true});
for(const viewport of [{width:390,height:844},{width:393,height:852}])for(const goal of ['reno','develop']){let p;const name=`WebKit ${viewport.width} ${goal} full journey`;try{p=await browser.newPage({viewport,isMobile:true,hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(`http://127.0.0.1:${server.address().port}/?fixtures=1`);await p.locator('[data-sample="fairlight-57"]').count().then(async n=>{if(n)await p.locator('[data-sample="fairlight-57"]').tap();else await p.locator('[data-sample]').first().tap()});await p.locator('#confirmProperty').tap();await p.locator('#manualDirections').evaluate(el=>el.open=true);await p.locator('#view-passport.active').waitFor();
if(goal==='reno'){await p.locator('#assistantInput').fill('I’m thinking about renovating my current property. I want to open up the kitchen, make the living area bigger and renovate my bathroom.');await p.locator('#assistantSend').tap();await p.locator('#confirmIntent').tap();assert.equal(await p.locator('#scopeArea').count(),0)}else{await p.locator('#passportPathways [data-goal="develop"]').tap();await p.locator('#developGrid [data-dev="duplex"]').tap();await p.locator('#feas-landValue').fill('4000000');await p.locator('#feas-salePerDwelling').fill('4000000')}
await p.locator('#runAssessment').tap();await p.locator('#view-assessment.active').waitFor();assert.equal(await p.locator('#assessmentDetail').getAttribute('open'),null);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.doesNotMatch(await p.locator('#consumerResult').innerText(),/Not available|externalWorks|authorityContributions|taxSensitivity|provider|fixture/);if(goal==='develop'){assert.match(await p.locator('#consumerResult').innerText(),/\$2,992,000/);assert.match(await p.locator('#consumerResult').innerText(),/\$8,000,000/)}await p.screenshot({path:`mobile-qa/${viewport.width}-${goal}.png`,fullPage:true});await p.locator('#assessmentDetail > summary').tap();for(const id of ['planning','cost','market','compare','risks'])assert.ok(await p.locator('#tab-'+id).isVisible());assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#toRoadmap').tap();await p.locator('#toReport').tap();await p.locator('#view-report.active').waitFor();assert.ok((await p.locator('#reportContent').innerText()).length>100);await p.locator('#restartBtn').tap();assert.equal(await p.locator('#assistantInput').inputValue(),'');assert.deepEqual(errors,[]);results.push({name,pass:true});console.log('PASS '+name)}catch(e){results.push({name,pass:false,error:e.stack});console.error('FAIL '+name+': '+e.message)}finally{await p?.close()}}
await browser.close();server.close();fs.writeFileSync('mobile-qa/results.json',JSON.stringify(results,null,2));process.exitCode=results.some(r=>!r.pass)?1:0})().catch(e=>{console.error(e);server.close();process.exitCode=1});
