'use strict';
const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),out=path.join(root,'qa-artifacts/residential');fs.mkdirSync(out,{recursive:true});
const live=!!process.env.SITEPIVOT_URL,server=live?null:require('./founder-server').createServer();
(async()=>{if(server)await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=process.env.SITEPIVOT_URL||`http://127.0.0.1:${server.address().port}/`,results=[];
for(const engine of [chromium,webkit]){const browser=await engine.launch();for(const width of [390,1280]){const page=await browser.newPage({viewport:{width,height:width<500?844:900},isMobile:width<500,hasTouch:width<500}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(45000);
try{await page.goto(base);assert.equal(await page.locator('#addressSearch').getAttribute('placeholder'),'Start typing your property address');
async function property(address){await page.locator('#addressSearch').fill(address);await page.locator('[data-live-index]').first().click();await page.locator('#view-property.active').waitFor();await page.locator('#confirmProperty').click();await page.locator('#view-passport.active').waitFor();await page.locator('#confirmBeds').fill('3');await page.locator('#confirmBaths').fill('2');await page.locator('#confirmCars').fill('1');await page.locator('#saveDwellingProfile').click();assert.equal(await page.locator('#saveDwellingProfile').count(),0,'Profile must confirm on one click');await page.waitForFunction(()=>SitePivot.app.property&&!SitePivot.app.property.planning.loading);}
if(live)await property('16 Eileen Street North Balgowlah');else await page.evaluate(()=>{const a=SitePivot,p=JSON.parse(JSON.stringify(a.FIXTURES[0]));Object.assign(p,{address:'16 Eileen Street, North Balgowlah NSW 2093',lot:'61',dp:'DP11915',area:471.3665155277003});p.planning={...p.planning,zone:'R2 Low Density Residential',instrument:'Warringah Local Environmental Plan 2011',fsr:null};a.selectProperty(p);a.show('passport')});
const evidence=await page.evaluate(()=>({address:SitePivot.app.property.address,lot:SitePivot.app.property.lot,dp:SitePivot.app.property.dp,area:SitePivot.app.property.area,planning:SitePivot.app.property.planning}));assert.match(evidence.address,/EILEEN|Eileen/);assert.ok(Math.abs(evidence.area-471.3665)<.3,JSON.stringify(evidence));assert.match(evidence.planning.zone,/R2/);assert.match(evidence.planning.instrument,/Warringah/);
async function say(t){await page.locator('#assistantInput').fill(t);await page.locator('#assistantSend').click()}
await say('I’m thinking about building a duplex here. Is that possible?');let text=await page.locator('#assistantMessages .assistant').last().innerText();assert.match(text,/471.4.*800/s);assert.match(text,/not a land-use prohibition/);assert.match(text,/LMR applicability is unresolved/);assert.equal(await page.locator('#confirmIntent').count(),0);assert.equal(await page.locator('#compareKeepingSelling').count(),0);
const blocked=await page.evaluate(()=>{const a=SitePivot,r=a.computeAssessment();return{cost:r.cost.mid,value:r.completed.mid,status:r.feas.status,eligibility:r.eligibility}});assert.equal(blocked.cost,null);assert.equal(blocked.value,null);assert.equal(blocked.status,'review');await page.screenshot({path:path.join(out,`${engine.name()}-${width}-eileen-planning.png`),fullPage:true});
await say('What other options do I have?');text=await page.locator('#assistantMessages .assistant').last().innerText();assert.match(text,/existing rooms.*extending.*level/s);assert.equal(await page.locator('#compareKeepingSelling').count(),0);
await say('Would I be better off selling and buying another property?');await page.locator('#compareKeepingSelling').click();await page.locator('#moveSale').fill('2000000');await page.locator('#targetPurchase').fill('2500000');await page.locator('#moveLoanBalance').fill('800000');await page.locator('#runAssessment').click();text=await page.locator('#consumerResult').innerText();for(const l of ['Equity available after selling','Cost to sell and buy','NSW transfer duty','Estimated additional funding'])assert.ok(text.includes(l),l);assert.doesNotMatch(text,/Indicative development profit|Total completed value/);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,`${engine.name()}-${width}-changeover.png`),fullPage:true});
if(live){await page.locator('#changeProperty').click();await property('1 Waratah Street Balgowlah');const mapped=await page.evaluate(()=>({address:SitePivot.app.property.address,lot:SitePivot.app.property.lot,dp:SitePivot.app.property.dp,fsr:SitePivot.app.property.planning.fsr,evidence:SitePivot.app.property.planning.fsrEvidence}));assert.equal(mapped.fsr,'0.6:1');assert.equal(mapped.evidence.state,'mapped');assert.match(mapped.evidence.provenance.instrument,/Manly Local Environmental Plan 2013/);await page.screenshot({path:path.join(out,`${engine.name()}-${width}-balgowlah-fsr.png`),fullPage:true});results.push({engine:engine.name(),width,pass:true,live,property:evidence,fsr:mapped});}else results.push({engine:engine.name(),width,pass:true,live,property:evidence});
assert.deepEqual(errors,[]);console.log('PASS residential '+engine.name()+' '+width+' '+(live?'live official property journey':'sourced dimensions regression'));}
catch(e){results.push({engine:engine.name(),width,pass:false,live,error:e.stack,pageErrors:errors});console.error(e.stack);await page.screenshot({path:path.join(out,`${engine.name()}-${width}-failure.png`),fullPage:true}).catch(()=>{});}finally{await page.close()}}await browser.close()}
fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));if(server)server.close();process.exitCode=results.some(x=>!x.pass)?1:0;})().catch(e=>{console.error(e);if(server)server.close();process.exitCode=1});
